special_days:
- name: service
  periods:
  - start: '2026-01-05'
    days: 1
  - start: '2026-01-26'
    days: 8
  - start: '2026-02-23'
    days: 8
  - start: '2026-03-23'
    days: 8
  - start: '2026-04-20'
    days: 8
  - start: '2026-05-18'
    days: 8
  - start: '2026-06-15'
    days: 8
  - start: '2026-07-13'
    days: 8
