shifts:
  - code: M
    start: "08:30"
    end: "17:30"
    paid_end: "17:30"
    tags: [weekday]
  - code: I
    start: "10:30"
    end: "19:30"
    paid_end: "19:30"
    tags: [weekday]
  - code: T
    start: "11:30"
    end: "20:30"
    paid_end: "20:30"
    tags: [weekday]

  - code: MW
    start: "08:30"
    end: "13:30"
    paid_end: "13:30"
    tags: [weekend, holiday]
  - code: IW
    start: "09:30"
    end: "16:30"
    paid_end: "16:30"
    tags: [weekend, holiday]
  - code: TW
    start: "15:30"
    end: "20:30"
    paid_end: "20:30"
    tags: [weekend, holiday]

  - code: MS
    start: "09:00"
    end: "18:00"
    paid_end: "18:00"
    tags: [service, weekday]
  - code: IS
    start: "13:00"
    end: "22:00"
    paid_end: "22:00"
    tags: [service, weekday]
  - code: TS
    start: "16:00"
    end: "23:59"
    paid_end: "00:00"
    clock_end_override: "23:59"
    tags: [service, weekday]
  - code: NS
    start: "00:00"
    end: "08:30"
    paid_end: "08:30"
    tags: [service, weekday, night]

  - code: MSW
    start: "08:30"
    end: "13:30"
    paid_end: "13:30"
    tags: [service, weekend, holiday]
  - code: ISW
    start: "14:00"
    end: "22:00"
    paid_end: "22:00"
    tags: [service, weekend, holiday]
  - code: TSW
    start: "16:00"
    end: "23:59"
    paid_end: "00:00"
    clock_end_override: "23:59"
    tags: [service, weekend, holiday]
  - code: NSW
    start: "00:00"
    end: "08:30"
    paid_end: "08:30"
    tags: [service, weekend, holiday, night]
  - code: FSW
    start: "09:30"
    end: "16:30"
    paid_end: "16:30"
    tags: [service, weekend, holiday, extra]
